### ISSUE TITLE
Bug: Missing topics page

### ISSUE THREAD

**Issue by gsakkis** [litestar-org/litestar-docs-preview#1]
### Description

The [topics](https://docs.litestar.dev/2/topics/index.html) and [sync-vs-async](https://docs.litestar.dev/2/topics/sync-vs-async.html) pages are missing.

### MCVE

```python
# Your MCVE code here
```

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

"In the format of: `![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)`"

### Litestar Version

2

### Platform

- [ ] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

**Comment by provinzkraut** [comment]
Hi @gsakkis, thanks for the report! 

In the future, please report the issues in the [litestar repository](https://github.com/litestar-org/litestar) directly, as this one is just for hosting a documentation preview for Pull Requests.

**Comment by provinzkraut** [comment]
It should be fixed now.
